# Generated by Django 3.1.3 on 2021-01-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210118_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
