# Generated by Django 3.1.3 on 2021-01-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subtitle',
        ),
    ]
